language: node_js
node_js:
  - 'node'
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build-uglify
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy_to_git.sh 'dist' "https://${GH_TOKEN}@github.com/qoomon/Jira-Issue-Card-Printer.git" 'gh-pages'
  on:
    branch: master
