language: node_js
node_js:
  - 'node'
before_script:
  - npm install
script:
  - |
    if [[ $TRAVIS_BRANCH =~ ^master$ ]]; then
      npm run gulp build

      cd 'dist'
      git init
      git branch -m gh-pages
      git add .
      git stash push
      git remote add origin 'https://${GH_TOKEN}@github.com/qoomon/Jira-Issue-Card-Printer.git'
      git pull --rebase origin gh-pages
      git stash pop
      git commit -m "Travis Build"
      echo git push origin gh-pages
    fi

env:
  global:
    secure: jWp5IJt8EjpHEWeeMuA4mAZtu5Pbc7R1h3ReUM6Y1JfFnRUfYHWDtBZGgIbOvls3+IQjoP9Wz+KK8P5npE4vElloQPqLRXmRAznwr/smb1kY0BfPMNrAbIgZjoaN994KhDqjzMWWk2qUzfS8tbkkZHQzE1NhG36nszHGeNTXarU=
