language: node_js
node_js:
  - 'node'
before_script:
  - npm install
script:
  - |
    if [[ $TRAVIS_BRANCH =~ ^master$ ]]; then
      npm run gulp build

      git clone --depth 1 -b 'gh-pages' --single-branch 'https://github.com/qoomon/Jira-Issue-Card-Printer.git' gh-pages
      cd 'gh-pages'
      git rm -r '*' --ignore-unmatch
      cp -R ../dist/ ./
      git add .
      git commit -m "Travis Build"
      git push
    fi

env:
  global:
    secure: jWp5IJt8EjpHEWeeMuA4mAZtu5Pbc7R1h3ReUM6Y1JfFnRUfYHWDtBZGgIbOvls3+IQjoP9Wz+KK8P5npE4vElloQPqLRXmRAznwr/smb1kY0BfPMNrAbIgZjoaN994KhDqjzMWWk2qUzfS8tbkkZHQzE1NhG36nszHGeNTXarU=
