language: node_js
node_js:
  - 'node'
cache:
  directories:
  - node_modules
before_script:
  - npm install
script:
  - npm run gulp build
  - if [[ $TRAVIS_BRANCH =~ ^master$ ]]; then ./deploy_dist_to_gh-pages.sh; fi

