language: node_js
node_js:
  - 'node'
cache:
  directories:
    - node_modules
install:
  - git config --global user.name "Travis"
  - git config --global user.email '<>'
  - npm install
before_script:
  - function on-branch { ([[ "$TRAVIS_BRANCH" =~ $1 ]] && shift && eval $@;) || echo 'ignored.';}
script:
  - npm run build
deploy:
  provider: script
  script: ./push_to_git.sh 'dist' "--- Source ---\nbranch ${TRAVIS_BRANCH}\n$(git show -s --format='short')" "https://qoomon:${GH_TOKEN}@github.com/qoomon/Jira-Issue-Card-Printer.git" 'gh-pages'
  on:
    branch: /^master$/