language: node_js
node_js:
  - 'node'
before_script:
  - npm install
script:
  - |
    if [[ $TRAVIS_BRANCH =~ ^master$ ]]; then
      npm run gulp build

      echo 'Deploy to "gh-pages"'
      git clone --depth 1 -b 'gh-pages' --single-branch "https://github.com/qoomon/Jira-Issue-Card-Printer.git" gh-pages
      cd 'gh-pages'
      git rm -r '*' --ignore-unmatch --quiet

      cp -R ../dist/* ./ 
      git add .

      git config user.name "travis"
      git config user.email "travis"
      git commit -m "Travis Build" -m "Source Branch $TRAVIS_BRANCH" -m "$(git show -s --format='short' )"

      git config push.default simple
      git push
    fi