language: node_js
node_js:
  - 'node'
cache:
  directories:
    - node_modules
install:
  - git config --global user.name "Travis"
  - git config --global user.email '<>'
  - npm install
script:
  - npm run build-uglify
  - if [[ "$TRAVIS_BRANCH" =~ ^master$ ]]; then ./push_to_git.sh 'dist' "https://qoomon:${GH_TOKEN}@github.com/qoomon/Jira-Issue-Card-Printer.git" 'gh-pages' "version> $(node -pe "require('./package.json').version")\nrepository> $(git config --get remote.origin.url)\nbranch> ${TRAVIS_BRANCH}\n$(git show -s --format='short')"; else echo 'ignored.'; fi
