language: node_js
node_js:
  - 'node'
cache:
  directories:
    - node_modules
before_install:
  - >-
    openssl aes-256-cbc 
    -K $encrypted_d4de8deaabc2_key 
    -iv $encrypted_d4de8deaabc2_iv 
    -in github_deploy_key.enc 
    -out github_deploy_key 
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
install:
  - npm ci
script:
  - npm run build -- --mode production
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy_to_git.sh 'dist' 'git@github.com:qoomon/Jira-Issue-Card-Printer.git' 'gh-pages'
  on:
    branch: master
    condition: $TRAVIS_REPO_SLUG = qoomon/Jira-Issue-Card-Printer
